apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "04.06.29"
          url: "docker.io/cbpautomation/python-hello-world-docker:04.06.29"
          digest: "sha256:d8b5ea1e7a00f4c44cbe72e65352103d6da7ee073e8727e5b07ef6526148bd53"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          target-environment: PROD
          artifact-id: ${{ steps.register.outputs.artifact-id }}
      - name: add_labels_to_artifact_version
        uses: cloudbees-io/label-artifact-version@v1
        with:
          artifact-id: ${{ steps.register.outputs.artifact-id }}
          labels: ready-to-test, ready-to-deploy
