apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "25.09.47"
          url: "docker.io/cbpautomation/python-hello-world-docker:25.09.47"
          digest: "sha256:e5b94dfe4f4da33cd6098504f915280c8b2b6405b9d002938e53958fc830c4bf"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          target-environment: PROD
          artifact-id: ${{ steps.register.outputs.artifact-id }}
      - name: add_labels_to_artifact_version
        uses: cloudbees-io/label-artifact-version@v1
        with:
          artifact-id: ${{ steps.register.outputs.artifact-id }}
          labels: ready-to-deploy, ready-to-test
