apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "25.10.24"
          url: "docker.io/cbpautomation/python-hello-world-docker:25.10.24"
          digest: "sha256:ae63c61aab613fd4dfd80cb18f1baf1903174547a28d78ed0eb09f1c66a390f2"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          target-environment: PROD
          artifact-id: ${{ steps.register.outputs.artifact-id }}
      - name: add_labels_to_artifact_version
        uses: cloudbees-io/label-artifact-version@v1
        with:
          artifact-id: ${{ steps.register.outputs.artifact-id }}
          labels: ready-to-test, ready-to-deploy
