apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.01.40"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.01.40"
          digest: "sha256:12e2662393af242d1af207e4ba21353c378d7bb1b8c39d0e195b9875a5dae6ab"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          target-environment: PROD
          artifact-id: ${{ steps.register.outputs.artifact-id }}
      - name: add_labels_to_artifact_version
        uses: cloudbees-io/label-artifact-version@v1
        with:
          artifact-id: ${{ steps.register.outputs.artifact-id }}
          labels: ready-to-test, ready-to-deploy
