apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "20.11.39"
          url: "docker.io/cbpautomation/python-hello-world-docker:20.11.39"
          digest: "sha256:647b4ed704f837db3bef97a4e09a86d849d08443853167788c6d9d548cd85fd3"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "PROD"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

