apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "10.06.56"
          url: "docker.io/cbpautomation/python-hello-world-docker:10.06.56"
          digest: "sha256:bd71564520dace21fc50c354a1a90aafd9a183b31a0c0757d53a5057ff9290e0"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "PROD"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

