apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "26.06.39"
          url: "docker.io/cbpautomation/python-hello-world-docker:26.06.39"
          digest: "sha256:9ed2b10f1b601df7a353c64c1812d0d56fbbb4bc21f3720f3b99278b48453250"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "PROD"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

