apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "31.01.44"
          url: "docker.io/cbpautomation/python-hello-world-docker:31.01.44"
          digest: "sha256:95d8c24ba25affd3c4741ddd25de9a2e6b888883abb046e91077560a67f1f21b"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "PROD"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

