apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "27.07.40"
          url: "docker.io/cbpautomation/python-hello-world-docker:27.07.40"
          digest: "sha256:202968c3aa830ea175e351dabfbad588048f48cbd28a40805f0911a0945fd268"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "PROD"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

